/**
 * 政令配置
 * 每个政令包含：
 * - id: 政令唯一标识
 * - name: 政令名称
 * - desc: 政令描述和效果
 * - cost: 行政成本
 * - active: 是否激活（初始状态）
 */
export const DECREES = [
  {
    id: 'clan_tribute',
    name: "部族贡粮",
    desc: "动员氏族共享余粮，防止断粮危机。",
    category: 'social',
    unlockEpoch: 0,
    cost: { admin: 4 },
    effects: ["每日 +1 粮食", "采集效率 +5%"],
    drawbacks: ["全局生产 -3%"],
    modifiers: { passive: { food: 1 }, categories: { gather: 0.05 }, production: -0.03 },
    active: false,
  },
  {
    id: 'grain_rationing',
    name: "粮食配给",
    desc: "严格管控粮仓,换取更稳定的口粮发放。",
    category: 'economy',
    unlockEpoch: 0,
    cost: { admin: 6 },
    effects: ["每日 +2 粮食"],
    drawbacks: ["全局生产 -5%"],
    modifiers: { passive: { food: 2 }, production: -0.05 },
    active: false,
  },
  {
    id: 'citizen_roadworks',
    name: "徭役筑路",
    desc: "征调公民维护道路，采集运输更加顺畅。",
    category: 'economy',
    unlockEpoch: 1,
    cost: { admin: 8 },
    effects: ["采集类建筑 +5%"],
    drawbacks: ["税收效率 -3%"],
    modifiers: { categories: { gather: 0.05 }, taxIncome: -0.03 },
    active: false,
  },
  { 
    id: 'forced_labor', 
    name: "强制劳动", 
    desc: "强迫佃农与矿工超时工作，换取短期增产。", 
    category: 'social',
    unlockEpoch: 3,
    cost: { admin: 10 }, 
    effects: ["矿井与庄园 +20% 产出"],
    drawbacks: ["佃农与矿工好感 -20/-15"],
    active: false 
  },
  { 
    id: 'tithe', 
    name: "什一税", 
    desc: "向神职人员征税，增加收入但降低其好感。", 
    category: 'culture',
    unlockEpoch: 3,
    cost: { admin: 5 }, 
    effects: ["定期征收神职人员财富"],
    drawbacks: ["神职好感 -10"],
    active: false 
  },
  {
    id: 'colonial_charter',
    name: "殖民特许",
    desc: "授予贸易公司海外特权，贸易港收益大增。",
    category: 'economy',
    unlockEpoch: 4,
    cost: { admin: 12 },
    effects: ["贸易港 +15%", "每日 +1 银币"],
    drawbacks: ["全局生产 -3%"],
    modifiers: { buildings: { trade_port: 0.15 }, passive: { silver: 1 }, production: -0.03 },
    active: false,
  },
  {
    id: 'press_freedom',
    name: "出版自由",
    desc: "允许民间刊物畅行，文化与舆论活跃。",
    category: 'culture',
    unlockEpoch: 5,
    cost: { admin: 10 },
    effects: ["咖啡馆、印刷所产出 +10%~15%"],
    drawbacks: ["税收效率 -5%"],
    modifiers: { buildings: { coffee_house: 0.1, printing_house: 0.15 }, taxIncome: -0.05 },
    active: false,
  },
  {
    id: 'workers_compact',
    name: "工人公约",
    desc: "改善工人待遇，换取工厂稳定运转。",
    category: 'social',
    unlockEpoch: 6,
    cost: { admin: 12 },
    effects: ["工业建筑 +10% 产出"],
    drawbacks: ["每日 -1 银币"],
    modifiers: { categories: { industry: 0.1 }, passive: { silver: -1 } },
    active: false 
  },
  // ========== 新增经济政令 ==========
  {
    id: 'market_regulation',
    name: "市场监管",
    desc: "建立市场监管机制，稳定物价波动，保护商人利益。",
    category: 'economy',
    unlockEpoch: 2,
    cost: { admin: 8 },
    effects: ["市场波动 -20%", "商人好感 +10"],
    drawbacks: ["贸易收益 -5%"],
    modifiers: { marketStability: 0.2, classApproval: { merchant: 10 }, tradeIncome: -0.05 },
    synergies: ['free_trade', 'guild_charter'],
    conflicts: ['state_monopoly'],
    active: false,
  },
  {
    id: 'free_trade',
    name: "自由贸易",
    desc: "取消贸易限制，鼓励商业往来，大幅提升贸易收益。",
    category: 'economy',
    unlockEpoch: 4,
    cost: { admin: 10 },
    effects: ["贸易收益 +25%", "每日 +2 银币"],
    drawbacks: ["市场波动 +15%", "本地工匠好感 -10"],
    modifiers: { tradeIncome: 0.25, passive: { silver: 2 }, marketVolatility: 0.15, classApproval: { artisan: -10 } },
    synergies: ['colonial_charter', 'market_regulation'],
    conflicts: ['state_monopoly', 'protectionism'],
    active: false,
  },
  {
    id: 'state_monopoly',
    name: "国家专营",
    desc: "政府垄断关键资源贸易，增加财政收入但抑制商业活力。",
    category: 'economy',
    unlockEpoch: 3,
    cost: { admin: 12 },
    effects: ["税收 +20%", "每日 +3 银币"],
    drawbacks: ["商人好感 -20", "贸易收益 -15%"],
    modifiers: { taxIncome: 0.2, passive: { silver: 3 }, classApproval: { merchant: -20 }, tradeIncome: -0.15 },
    conflicts: ['free_trade', 'market_regulation'],
    active: false,
  },
  {
    id: 'guild_charter',
    name: "行会特许",
    desc: "授予工匠行会自治权，提升手工业产出和质量。",
    category: 'economy',
    unlockEpoch: 2,
    cost: { admin: 7 },
    effects: ["工匠产出 +15%", "工匠好感 +15"],
    drawbacks: ["工具成本 +10%"],
    modifiers: { categories: { craft: 0.15 }, classApproval: { artisan: 15 }, resourceCost: { tools: 0.1 } },
    synergies: ['market_regulation', 'apprentice_system'],
    active: false,
  },
  {
    id: 'protectionism',
    name: "贸易保护",
    desc: "征收高额关税，保护本国产业，但限制国际贸易。",
    category: 'economy',
    unlockEpoch: 4,
    cost: { admin: 9 },
    effects: ["本地生产 +10%", "税收 +15%"],
    drawbacks: ["贸易收益 -20%", "外交关系 -10"],
    modifiers: { production: 0.1, taxIncome: 0.15, tradeIncome: -0.2, diplomacy: -10 },
    conflicts: ['free_trade', 'colonial_charter'],
    active: false,
  },
  // ========== 新增军事政令 ==========
  {
    id: 'conscription_law',
    name: "征兵法",
    desc: "实施全民征兵制度，快速扩充军队规模。",
    category: 'military',
    unlockEpoch: 3,
    cost: { admin: 10 },
    effects: ["征兵速度 +40%", "军队上限 +30%"],
    drawbacks: ["全局生产 -10%", "民众好感 -15"],
    modifiers: { recruitSpeed: 0.4, armyCapacity: 0.3, production: -0.1, classApproval: { peasant: -15, serf: -15 } },
    synergies: ['military_academy', 'war_economy'],
    conflicts: ['professional_army'],
    active: false,
  },
  {
    id: 'professional_army',
    name: "职业军队",
    desc: "建立精锐的职业军队，战斗力强但维护成本高。",
    category: 'military',
    unlockEpoch: 4,
    cost: { admin: 12 },
    effects: ["军队战力 +30%", "士气 +20"],
    drawbacks: ["军队维护 +40%", "征兵速度 -20%"],
    modifiers: { militaryPower: 0.3, morale: 20, militaryCost: 0.4, recruitSpeed: -0.2 },
    synergies: ['military_academy', 'officer_corps'],
    conflicts: ['conscription_law'],
    active: false,
  },
  {
    id: 'military_academy',
    name: "军事学院",
    desc: "建立军官培训体系，提升军队素质和指挥能力。",
    category: 'military',
    unlockEpoch: 5,
    cost: { admin: 11 },
    effects: ["军队战力 +20%", "科研 +0.5/日"],
    drawbacks: ["每日 -2 银币"],
    modifiers: { militaryPower: 0.2, passive: { science: 0.5, silver: -2 } },
    synergies: ['professional_army', 'conscription_law'],
    active: false,
  },
  {
    id: 'war_economy',
    name: "战时经济",
    desc: "将经济转向战争生产，大幅提升军事产出。",
    category: 'military',
    unlockEpoch: 6,
    cost: { admin: 14 },
    effects: ["军事生产 +50%", "征兵速度 +30%"],
    drawbacks: ["民用生产 -20%", "民众好感 -20"],
    modifiers: { categories: { military: 0.5 }, recruitSpeed: 0.3, production: -0.2, stability: -10 },
    synergies: ['conscription_law', 'state_monopoly'],
    active: false,
  },
  {
    id: 'officer_corps',
    name: "军官团制",
    desc: "建立贵族军官团，提升指挥效率和军队忠诚度。",
    category: 'military',
    unlockEpoch: 4,
    cost: { admin: 9 },
    effects: ["军队战力 +15%", "贵族好感 +20"],
    drawbacks: ["军队维护 +20%"],
    modifiers: { militaryPower: 0.15, classApproval: { noble: 20 }, militaryCost: 0.2 },
    synergies: ['professional_army'],
    active: false,
  },
  // ========== 新增文化政令 ==========
  {
    id: 'public_education',
    name: "公共教育",
    desc: "建立公共教育体系，提升民众素质和科研能力。",
    category: 'culture',
    unlockEpoch: 5,
    cost: { admin: 13 },
    effects: ["科研 +30%", "文化 +20%", "全阶层好感 +5"],
    drawbacks: ["每日 -3 银币"],
    modifiers: { scienceBonus: 0.3, cultureBonus: 0.2, classApproval: { all: 5 }, passive: { silver: -3 } },
    synergies: ['press_freedom', 'university_charter'],
    active: false,
  },
  {
    id: 'university_charter',
    name: "大学特许",
    desc: "授予大学自治权，吸引学者，推动学术发展。",
    category: 'culture',
    unlockEpoch: 4,
    cost: { admin: 10 },
    effects: ["科研 +25%", "学者好感 +20"],
    drawbacks: ["文化产出 -5%"],
    modifiers: { scienceBonus: 0.25, classApproval: { scribe: 20, scholar: 20 }, cultureBonus: -0.05 },
    synergies: ['public_education', 'press_freedom'],
    active: false,
  },
  {
    id: 'state_religion',
    name: "国教制度",
    desc: "确立国家宗教，增强文化凝聚力和神职人员影响力。",
    category: 'culture',
    unlockEpoch: 3,
    cost: { admin: 8 },
    effects: ["文化 +20%", "神职好感 +25", "稳定度 +10"],
    drawbacks: ["科研 -10%", "其他宗教好感 -20"],
    modifiers: { cultureBonus: 0.2, classApproval: { cleric: 25 }, stability: 10, scienceBonus: -0.1 },
    synergies: ['tithe', 'religious_tolerance'],
    conflicts: ['secular_state'],
    active: false,
  },
  {
    id: 'secular_state',
    name: "世俗国家",
    desc: "政教分离，削弱宗教影响，促进理性思考。",
    category: 'culture',
    unlockEpoch: 5,
    cost: { admin: 11 },
    effects: ["科研 +25%", "神职好感 -30"],
    drawbacks: ["文化 -10%", "稳定度 -5"],
    modifiers: { scienceBonus: 0.25, classApproval: { cleric: -30 }, cultureBonus: -0.1, stability: -5 },
    conflicts: ['state_religion', 'tithe'],
    active: false,
  },
  {
    id: 'religious_tolerance',
    name: "宗教宽容",
    desc: "允许多种信仰共存，吸引移民和商人。",
    category: 'culture',
    unlockEpoch: 4,
    cost: { admin: 9 },
    effects: ["人口增长 +15%", "商人好感 +15", "外交 +10"],
    drawbacks: ["神职好感 -10"],
    modifiers: { populationGrowth: 0.15, classApproval: { merchant: 15, cleric: -10 }, diplomacy: 10 },
    synergies: ['state_religion', 'free_trade'],
    active: false,
  },
  {
    id: 'cultural_patronage',
    name: "文化赞助",
    desc: "国家资助艺术家和学者，繁荣文化事业。",
    category: 'culture',
    unlockEpoch: 3,
    cost: { admin: 8 },
    effects: ["文化 +30%", "艺术家好感 +20"],
    drawbacks: ["每日 -2 银币"],
    modifiers: { cultureBonus: 0.3, classApproval: { artist: 20, scribe: 15 }, passive: { silver: -2 } },
    synergies: ['press_freedom', 'public_education'],
    active: false,
  },
  // ========== 新增社会政令 ==========
  {
    id: 'land_reform',
    name: "土地改革",
    desc: "重新分配土地，削弱地主权力，提升农民地位。",
    category: 'social',
    unlockEpoch: 4,
    cost: { admin: 15 },
    effects: ["农民好感 +30", "粮食产出 +20%"],
    drawbacks: ["地主好感 -40", "稳定度 -15"],
    modifiers: { classApproval: { peasant: 30, landowner: -40 }, categories: { gather: 0.2 }, stability: -15 },
    conflicts: ['feudal_privileges'],
    active: false,
  },
  {
    id: 'feudal_privileges',
    name: "封建特权",
    desc: "维护贵族和地主的传统特权，稳定社会秩序。",
    category: 'social',
    unlockEpoch: 3,
    cost: { admin: 7 },
    effects: ["贵族好感 +25", "地主好感 +20", "稳定度 +10"],
    drawbacks: ["农民好感 -20", "税收 -10%"],
    modifiers: { classApproval: { noble: 25, landowner: 20, peasant: -20 }, stability: 10, taxIncome: -0.1 },
    conflicts: ['land_reform', 'equality_decree'],
    active: false,
  },
  {
    id: 'equality_decree',
    name: "平等法令",
    desc: "宣布人人平等，废除阶级特权，引发社会变革。",
    category: 'social',
    unlockEpoch: 5,
    cost: { admin: 16 },
    effects: ["下层阶级好感 +20", "生产力 +15%"],
    drawbacks: ["上层阶级好感 -30", "稳定度 -20"],
    modifiers: { 
      classApproval: { peasant: 20, worker: 20, serf: 20, noble: -30, landowner: -30, merchant: -20 }, 
      production: 0.15, 
      stability: -20 
    },
    conflicts: ['feudal_privileges', 'aristocratic_rule'],
    active: false,
  },
  {
    id: 'apprentice_system',
    name: "学徒制度",
    desc: "规范学徒培训体系，提升技术传承和工匠素质。",
    category: 'social',
    unlockEpoch: 2,
    cost: { admin: 6 },
    effects: ["工匠产出 +10%", "工人好感 +10"],
    drawbacks: ["培训成本增加"],
    modifiers: { categories: { craft: 0.1 }, classApproval: { artisan: 10, worker: 10 } },
    synergies: ['guild_charter', 'public_education'],
    active: false,
  },
  {
    id: 'welfare_system',
    name: "福利制度",
    desc: "建立社会福利体系，保障民众基本生活。",
    category: 'social',
    unlockEpoch: 6,
    cost: { admin: 14 },
    effects: ["全阶层好感 +15", "人口增长 +20%", "稳定度 +15"],
    drawbacks: ["每日 -5 银币"],
    modifiers: { classApproval: { all: 15 }, populationGrowth: 0.2, stability: 15, passive: { silver: -5 } },
    synergies: ['public_education', 'workers_compact'],
    active: false,
  },
  {
    id: 'aristocratic_rule',
    name: "贵族统治",
    desc: "强化贵族统治地位，提升行政效率但加剧阶级矛盾。",
    category: 'social',
    unlockEpoch: 3,
    cost: { admin: 8 },
    effects: ["行政容量 +20%", "贵族好感 +30"],
    drawbacks: ["平民好感 -15", "税收效率 -10%"],
    modifiers: { adminCapacity: 0.2, classApproval: { noble: 30, peasant: -15, worker: -15 }, taxIncome: -0.1 },
    conflicts: ['equality_decree'],
    active: false,
  },
  // ========== 新增科技政令 ==========
  {
    id: 'research_grants',
    name: "科研资助",
    desc: "政府大力资助科学研究，加速技术进步。",
    category: 'science',
    unlockEpoch: 4,
    cost: { admin: 12 },
    effects: ["科研 +40%", "学者好感 +25"],
    drawbacks: ["每日 -4 银币"],
    modifiers: { scienceBonus: 0.4, classApproval: { scribe: 25, scholar: 25 }, passive: { silver: -4 } },
    synergies: ['university_charter', 'public_education'],
    active: false,
  },
  {
    id: 'patent_law',
    name: "专利法",
    desc: "保护发明创造，鼓励技术创新和工业发展。",
    category: 'science',
    unlockEpoch: 5,
    cost: { admin: 10 },
    effects: ["科研 +20%", "工业产出 +15%"],
    drawbacks: ["技术传播 -10%"],
    modifiers: { scienceBonus: 0.2, categories: { industry: 0.15 }, techSpread: -0.1 },
    synergies: ['research_grants', 'guild_charter'],
    active: false,
  },
  {
    id: 'infrastructure_plan',
    name: "基建计划",
    desc: "大规模投资基础设施，提升整体生产效率。",
    category: 'economy',
    unlockEpoch: 5,
    cost: { admin: 15 },
    effects: ["全局生产 +20%", "采集效率 +15%"],
    drawbacks: ["每日 -6 银币", "初期稳定度 -10"],
    modifiers: { production: 0.2, categories: { gather: 0.15 }, passive: { silver: -6 }, stability: -10 },
    synergies: ['citizen_roadworks', 'war_economy'],
    active: false,
  },
];
