/**
 * 科技树配置
 * 每个科技包含：
 * - id: 科技唯一标识
 * - name: 科技名称
 * - desc: 科技描述和效果
 * - cost: 研究成本
 * - epoch: 解锁时代
 */
export const TECHS = [
  // 石器时代
  {
    id: 'barter',
    name: "物物交换",
    desc: "允许建造贸易站，让商人阶层登上历史舞台。",
    cost: { science: 50 },
    epoch: 0,
  },
  {
    id: 'stone_axes',
    name: "磨制石斧",
    desc: "伐木场产出提升 25%。",
    cost: { science: 50 },
    epoch: 0,
    effects: { buildings: { lumber_camp: 0.25 } },
  },
  {
    id: 'flint_knapping',
    name: "打制燧石",
    desc: "采石场效率增加 25%。",
    cost: { science: 70 },
    epoch: 0,
    effects: { buildings: { quarry: 0.25 } },
  },
  {
    id: 'animal_husbandry',
    name: "畜牧业",
    desc: "驯养牲畜，每日额外获得 20 点粮食。",
    cost: { science: 80 },
    epoch: 0,
    effects: { passive: { food: 20 } },
  },
  {
    id: 'pottery',
    name: "陶器",
    desc: "农田储粮效率 +10%。",
    cost: { science: 100 },
    epoch: 0,
    effects: { buildings: { farm: 0.1 } },
  },
  {
    id: 'tool_making',
    name: "工具制作",
    desc: "解锁石器作坊，提供早期稳定的工具来源。",
    cost: { science: 90 },
    epoch: 0,
  },
  {
    id: 'basic_irrigation',
    name: "基础灌溉",
    desc: "开凿浅渠把河水引入农田，产量提升 15%。",
    cost: { science: 120 },
    epoch: 0,
    effects: { buildings: { farm: 0.15 } },
  },
  {
    id: 'oral_tradition',
    name: "口述传统",
    desc: "长者口述史诗，图书馆的整理效率提升 15%。",
    cost: { science: 110 },
    epoch: 0,
    effects: { buildings: { library: 0.15 } },
  },
  {
    id: 'communal_granary',
    name: "公共粮仓",
    desc: "人口上限 +10。",
    cost: { science: 130 },
    epoch: 0,
    effects: { maxPop: 10 },
  },

  {
    id: 'river_fishing',
    name: "河湾捕鱼",
    desc: "每日额外获得 10 粮食与 0.2 银币。",
    cost: { science: 150 },
    epoch: 0,
    effects: { passive: { food: 10, silver: 0.2 } },
  },
  {
    id: 'wheel',
    name: "车轮",
    desc: "采集建筑整体效率 +20%。",
    cost: { science: 160 },
    epoch: 0,
    effects: { categories: { gather: 0.2 } },
  },

  // 青铜时代
  {
    id: 'tools',
    name: "铜制工具",
    desc: "允许建造锯木厂，工业效率 +5%。",
    cost: { science: 250 },
    epoch: 1,
    effects: { categories: { industry: 0.05 } },
  },
  {
    id: 'copper_mining',
    name: "铜脉勘探",
    desc: "铜矿效率 +25%。",
    cost: { science: 280 },
    epoch: 1,
    effects: { buildings: { copper_mine: 0.25 } },
  },
  {
    id: 'bronze_working',
    name: "青铜冶炼",
    desc: "青铜铸坊产出 +30%，铁矿井同步获得 +15%。",
    cost: { science: 320 },
    epoch: 1,
    effects: { buildings: { bronze_foundry: 0.3, mine: 0.15 } },
  },
  {
    id: 'horse_collar',
    name: "牛项圈",
    desc: "农田与庄园增产 10%。",
    cost: { science: 260 },
    epoch: 1,
    effects: { buildings: { farm: 0.1, large_estate: 0.1 } },
  },
  {
    id: 'caravan_trade',
    name: "驼队贸易",
    desc: "市场银币收入 +35%。",
    cost: { science: 300 },
    epoch: 1,
    effects: { buildings: { market: 0.35 } },
  },
  {
    id: 'granary_architecture',
    name: "粮仓结构",
    desc: "粮仓产出 +25%，并额外提供 +5 人口上限。",
    cost: { science: 320 },
    epoch: 1,
    effects: { buildings: { granary: 0.25 }, maxPop: 5 },
  },

  {
    id: 'ritual_priesthood',
    name: "仪式司祭",
    desc: "礼拜设施文化产出提升 15%。",
    cost: { science: 340 },
    epoch: 3,
    effects: { buildings: { church: 0.15 } },
  },

  // 古典时代
  {
    id: 'papyrus_cultivation',
    name: "改进造纸术",
    desc: "造纸工坊效率 +20%。",
    cost: { science: 450 },
    epoch: 2,
    effects: { buildings: { reed_works: 0.2 } },
  },
  {
    id: 'culinary_arts',
    name: "烹饪艺术",
    desc: "解锁烹饪坊，将粮食加工为珍馐，满足上层阶级的饮食需求。",
    cost: { science: 480 },
    epoch: 2,
    effects: { buildings: { culinary_kitchen: 0.2 } },
  },
  {
    id: 'brewing',
    name: "酿造工艺",
    desc: "解锁酿造坊，将粮食发酵为美酒，供贸易与享用。",
    cost: { science: 460 },
    epoch: 2,
    effects: { buildings: { brewery: 0.2 } },
  },
  {
    id: 'carpentry',
    name: "精细木工",
    desc: "解锁家具工坊，将木材与石料加工为精美家具，提升上层阶级的生活品质。",
    cost: { science: 500 },
    epoch: 2,
    effects: { buildings: { furniture_workshop: 0.2 } },
  },
  {
    id: 'library_catalogs',
    name: "图书编目",
    desc: "图书馆科研 +25%。",
    cost: { science: 470 },
    epoch: 2,
    effects: { buildings: { library: 0.25 } },
  },
  {
    id: 'amphitheater_design',
    name: "剧场设计",
    desc: "解锁剧场建筑，且剧场文化产出 +30%。",
    cost: { science: 490 },
    epoch: 1,
    effects: { buildings: { amphitheater: 0.3 } },
  },
  {
    id: 'urban_planning',
    name: "城市规划",
    desc: "木屋效率 +20%，人口上限 +10。",
    cost: { science: 520 },
    epoch: 2,
    effects: { buildings: { house: 0.2 }, maxPop: 10 },
  },
  {
    id: 'republican_code',
    name: "共和法典",
    desc: "提升法律体系。",
    cost: { science: 560 },
    epoch: 2,
    effects: {},
  },
  {
    id: 'road_system',
    name: "道路网络",
    desc: "采集作业效率 +10%。",
    cost: { science: 600 },
    epoch: 2,
    effects: { categories: { gather: 0.1 } },
  },

  // 封建时代
  {
    id: 'feudalism',
    name: "封建制度",
    desc: "庄园耕作效率 +15%。",
    cost: { science: 1000 },
    epoch: 3,
    effects: { buildings: { large_estate: 0.15 } },
  },
  {
    id: 'theology',
    name: "神学",
    desc: "教堂文化产出 +30%。",
    cost: { science: 1100 },
    epoch: 3,
    effects: { buildings: { church: 0.3 } },
  },
  {
    id: 'bureaucracy',
    name: "官僚制度",
    desc: "解锁市政厅。",
    cost: { science: 1200 },
    epoch: 3,
    effects: {},
  },
  {
    id: 'three_field_system',
    name: "三圃制",
    desc: "农田与庄园额外 +15% 产量。",
    cost: { science: 1100 },
    epoch: 3,
    effects: { buildings: { farm: 0.15, large_estate: 0.15 } },
  },
  {
    id: 'stone_keep_engineering',
    name: "石垒堡舍",
    desc: "居住建筑人口上限加成 10%。",
    cost: { science: 1150 },
    epoch: 3,
    effects: { buildings: { hut: 0.1, house: 0.1 } },
  },
  {
    id: 'ironworking',
    name: "锻铁术",
    desc: "解锁铁器铺，并且铁矿井效率 +30%。",
    cost: { science: 1500 },
    epoch: 2,
    effects: { buildings: { mine: 0.3 } },
  },

  // 探索时代
  {
    id: 'cartography',
    name: "海图绘制",
    desc: "船坞香料获取 +25%。",
    cost: { science: 1800 },
    epoch: 4,
    effects: { buildings: { dockyard: 0.25 } },
  },
  {
    id: 'charter_companies',
    name: "特许公司",
    desc: "贸易港银币产出 +30%，并每日被动 +1 银币。",
    cost: { science: 1900 },
    epoch: 4,
    effects: { buildings: { trade_port: 0.3 }, passive: { silver: 1 } },
  },
  {
    id: 'navigator_schooling',
    name: "领航学",
    desc: "航海学院科研提升 30%。",
    cost: { science: 2000 },
    epoch: 4,
    effects: { buildings: { navigator_school: 0.3 } },
  },
  {
    id: 'naval_artillery',
    name: "舰炮试验",
    desc: "船坞额外获得 15% 产量。",
    cost: { science: 2100 },
    epoch: 4,
    effects: { buildings: { dockyard: 0.15 } },
  },
  {
    id: 'colonial_ledgers',
    name: "殖民档案",
    desc: "提升殖民地管理。",
    cost: { science: 2200 },
    epoch: 4,
    effects: {},
  },
  {
    id: 'spice_monopolies',
    name: "香料垄断",
    desc: "贸易港再获 15% 产量。",
    cost: { science: 2300 },
    epoch: 4,
    effects: { buildings: { trade_port: 0.15 } },
  },

  // 启蒙时代
  {
    id: 'coffee_agronomy',
    name: "咖啡栽培学",
    desc: "咖啡种植园效率 +30%。",
    cost: { science: 3200 },
    epoch: 5,
    effects: { buildings: { coffee_plantation: 0.3 } },
  },
  {
    id: 'coffeehouse_philosophy',
    name: "咖啡馆哲学",
    desc: "咖啡馆文化 +35%，被动 +0.4 文化。",
    cost: { science: 3400 },
    epoch: 5,
    effects: { buildings: { coffee_house: 0.35 }, passive: { culture: 0.4 } },
  },
  {
    id: 'printing_press',
    name: "印刷机",
    desc: "解锁印刷所并提升 35% 产量。",
    cost: { science: 3600 },
    epoch: 5,
    effects: { buildings: { printing_house: 0.35 } },
  },
  {
    id: 'public_schooling',
    name: "公共教育",
    desc: "图书馆 +25% 科研，被动 +0.2 文化。",
    cost: { science: 3800 },
    epoch: 5,
    effects: { buildings: { library: 0.25 }, passive: { culture: 0.2 } },
  },
  {
    id: 'social_contract',
    name: "社会契约",
    desc: "提升社会组织效率。",
    cost: { science: 4000 },
    epoch: 5,
    effects: {},
  },
  {
    id: 'salon_debates',
    name: "沙龙辩论",
    desc: "剧场文化再增 15%。",
    cost: { science: 4200 },
    epoch: 5,
    effects: { buildings: { amphitheater: 0.15 } },
  },

  // 工业时代
  {
    id: 'coal_gasification',
    name: "煤气化",
    desc: "煤矿效率 +30%。",
    cost: { science: 5200 },
    epoch: 6,
    effects: { buildings: { coal_mine: 0.3 } },
  },
  {
    id: 'steel_alloys',
    name: "钢合金",
    desc: "炼钢厂效率 +30%。",
    cost: { science: 5400 },
    epoch: 6,
    effects: { buildings: { steel_foundry: 0.3 } },
  },
  {
    id: 'industrialization',
    name: "工业化",
    desc: "解锁工厂，工业建筑效率 +10%。",
    cost: { science: 6000 },
    epoch: 6,
    effects: { categories: { industry: 0.1 } },
  },
  {
    id: 'steam_power',
    name: "蒸汽动力",
    desc: "工业建筑再获 +20% 产量。",
    cost: { science: 6400 },
    epoch: 6,
    effects: { categories: { industry: 0.2 } },
  },
  {
    id: 'chemical_fertilizer',
    name: "化学施肥",
    desc: "农田与庄园 +20% 产出。",
    cost: { science: 6000 },
    epoch: 6,
    effects: { buildings: { farm: 0.2, large_estate: 0.2 } },
  },
  {
    id: 'rail_network',
    name: "铁路网",
    desc: "铁路枢纽效率 +30%，采集 +10%。",
    cost: { science: 6200 },
    epoch: 6,
    effects: { buildings: { rail_depot: 0.3 }, categories: { gather: 0.1 } },
  },
  {
    id: 'precision_tools',
    name: "精密机具",
    desc: "工厂产出 +25%。",
    cost: { science: 6400 },
    epoch: 6,
    effects: { buildings: { factory: 0.25 } },
  },
  
  // 军事科技
  {
    id: 'military_training',
    name: "军事训练",
    desc: "解锁训练场，提供更多军事容量。",
    cost: { science: 800 },
    epoch: 2,
  },
  {
    id: 'fortification',
    name: "要塞工程",
    desc: "解锁要塞，大幅提升军事容量。",
    cost: { science: 2400 },
    epoch: 4,
  },

  // ========== 高级工业科技 ==========
  
  // 纺织产业升级科技
  {
    id: 'mechanized_weaving',
    name: "机械织布",
    desc: "解锁纺织厂，水力驱动的飞梭织机大幅提升布料产量。",
    cost: { science: 3000 },
    epoch: 5,
    effects: { buildings: { loom_house: 0.20, tailor_workshop: 0.15 } },
  },
  {
    id: 'assembly_line',
    name: "流水线生产",
    desc: "解锁服装工厂，标准化分工使产量翻倍。",
    cost: { science: 5800 },
    epoch: 6,
    effects: { buildings: { textile_mill: 0.25, garment_factory: 0.20 } },
  },
  
  // 木材加工产业升级科技
  {
    id: 'hydraulic_sawing',
    name: "水力锯切",
    desc: "解锁木材加工厂，水轮驱动的圆锯效率远超手工。",
    cost: { science: 2800 },
    epoch: 5,
    effects: { buildings: { sawmill: 0.25, lumber_camp: 0.15 } },
  },
  {
    id: 'mass_production',
    name: "大规模生产",
    desc: "解锁家具工厂，标准化零件实现批量生产。",
    cost: { science: 5600 },
    epoch: 6,
    effects: { buildings: { lumber_mill: 0.20, furniture_workshop: 0.25 } },
  },
  
  // 冶金产业升级科技
  {
    id: 'advanced_metallurgy',
    name: "先进冶金",
    desc: "解锁冶金工坊，改良熔炉与合金配方提升工具质量。",
    cost: { science: 2200 },
    epoch: 4,
    effects: { buildings: { iron_tool_workshop: 0.20, bronze_foundry: 0.15 } },
  },
  {
    id: 'bessemer_process',
    name: "贝塞麦炼钢法",
    desc: "解锁钢铁联合体，吹入空气快速去碳，钢铁产量剧增。",
    cost: { science: 6200 },
    epoch: 6,
    effects: { buildings: { steel_foundry: 0.30, metallurgy_workshop: 0.25 } },
  },
  
  // 建材产业升级科技
  {
    id: 'industrial_ceramics',
    name: "工业陶瓷",
    desc: "解锁建材厂，环形窑与传送带实现连续烧制。",
    cost: { science: 2600 },
    epoch: 5,
    effects: { buildings: { brickworks: 0.25 } },
  },
  {
    id: 'standardized_construction',
    name: "标准化建筑",
    desc: "解锁预制构件厂，预制构件加速建设、降低成本。",
    cost: { science: 5400 },
    epoch: 6,
    effects: { buildings: { building_materials_plant: 0.25 }, maxPop: 15 },
  },
  
  // 食品加工产业升级科技
  {
    id: 'food_preservation',
    name: "食品保鲜",
    desc: "解锁罐头厂，密封罐装技术延长食品保质期。",
    cost: { science: 5000 },
    epoch: 6,
    effects: { buildings: { culinary_kitchen: 0.25 } },
  },
  {
    id: 'distillation',
    name: "蒸馏技术",
    desc: "解锁蒸馏酒厂，分离提纯出高度烈酒。",
    cost: { science: 3200 },
    epoch: 5,
    effects: { buildings: { brewery: 0.30 } },
  },
  
  // 造纸印刷产业升级科技
  {
    id: 'wood_pulp_process',
    name: "木浆造纸",
    desc: "解锁造纸厂，木材纤维取代手工纸浆，产量倍增。",
    cost: { science: 2900 },
    epoch: 5,
    effects: { buildings: { reed_works: 0.30 } },
  },
  {
    id: 'mass_media',
    name: "大众传媒",
    desc: "解锁出版社，报纸杂志覆盖全民，舆论力量崛起。",
    cost: { science: 5500 },
    epoch: 6,
    effects: { buildings: { printing_house: 0.30, publishing_house: 0.20 } },
  },
  
  // 高级采集科技
  {
    id: 'deep_shaft_mining',
    name: "深井采矿",
    desc: "解锁工业矿场，蒸汽泵排水、铁轨运矿，开采深层矿脉。",
    cost: { science: 5200 },
    epoch: 6,
    effects: { buildings: { mine: 0.25, coal_mine: 0.20 } },
  },
  {
    id: 'agricultural_machinery',
    name: "农业机械",
    desc: "解锁机械化农场，蒸汽拖拉机与收割机解放大量人力。",
    cost: { science: 5600 },
    epoch: 6,
    effects: { buildings: { farm: 0.25, large_estate: 0.30 } },
  },
  {
    id: 'steam_logging',
    name: "蒸汽伐木",
    desc: "解锁伐木公司，蒸汽锯与窄轨铁路运输原木。",
    cost: { science: 5000 },
    epoch: 6,
    effects: { buildings: { lumber_camp: 0.30 } },
  },
  
  // 高级文化与城市科技
  {
    id: 'higher_education',
    name: "高等教育",
    desc: "解锁大学，系统化培养专业人才。",
    cost: { science: 3500 },
    epoch: 5,
    effects: { buildings: { library: 0.20, navigator_school: 0.20 } },
  },
  {
    id: 'grand_arts',
    name: "高雅艺术",
    desc: "解锁歌剧院，戏剧与音乐的殿堂。",
    cost: { science: 3800 },
    epoch: 5,
    effects: { buildings: { amphitheater: 0.25, church: 0.15 } },
  },
  {
    id: 'urban_architecture',
    name: "城市建筑学",
    desc: "解锁公寓楼，多层建筑容纳更多城市人口。",
    cost: { science: 5800 },
    epoch: 6,
    effects: { buildings: { house: 0.20 }, maxPop: 20 },
  },
  {
    id: 'financial_capitalism',
    name: "金融资本主义",
    desc: "解锁证券交易所，股票与债券调配社会资本。",
    cost: { science: 6500 },
    epoch: 6,
    effects: { buildings: { trade_port: 0.20, rail_depot: 0.15 }, passive: { silver: 2 } },
  },
];
