export const THREE_KINGDOMS_GENERALS = [
    { id: 'g_cao_cao', name: '曹操', factionId: 'cao_cao', leadership: 92, strategy: 95, politics: 90, loyalty: 90 },
    { id: 'g_xiahou_dun', name: '夏侯惇', factionId: 'cao_cao', leadership: 86, strategy: 75, politics: 62, loyalty: 88 },
    { id: 'g_liu_bei', name: '刘备', factionId: 'liu_bei', leadership: 85, strategy: 82, politics: 88, loyalty: 92 },
    { id: 'g_guan_yu', name: '关羽', factionId: 'liu_bei', leadership: 93, strategy: 78, politics: 60, loyalty: 95 },
    { id: 'g_zhang_fei', name: '张飞', factionId: 'liu_bei', leadership: 91, strategy: 68, politics: 45, loyalty: 94 },
    { id: 'g_sun_jian', name: '孙坚', factionId: 'sun_jian', leadership: 88, strategy: 80, politics: 62, loyalty: 86 },
    { id: 'g_sun_ce', name: '孙策', factionId: 'sun_jian', leadership: 90, strategy: 83, politics: 58, loyalty: 89 },
    { id: 'g_yuan_shao', name: '袁绍', factionId: 'yuan_shao', leadership: 75, strategy: 70, politics: 68, loyalty: 70 },
    { id: 'g_yan_liang', name: '颜良', factionId: 'yuan_shao', leadership: 84, strategy: 58, politics: 40, loyalty: 82 },
    { id: 'g_dong_zhuo', name: '董卓', factionId: 'dong_zhuo', leadership: 70, strategy: 52, politics: 35, loyalty: 45 },
    { id: 'g_lv_bu', name: '吕布', factionId: 'dong_zhuo', leadership: 98, strategy: 50, politics: 28, loyalty: 30 },
    { id: 'g_zhou_yu', name: '周瑜', factionId: 'sun_jian', leadership: 88, strategy: 94, politics: 84, loyalty: 90 },
    { id: 'g_ma_teng', name: '马腾', factionId: 'ma_teng', leadership: 82, strategy: 68, politics: 50, loyalty: 80 },
    { id: 'g_han_sui', name: '韩遂', factionId: 'han_sui', leadership: 78, strategy: 66, politics: 52, loyalty: 62 },
    { id: 'g_zhang_lu', name: '张鲁', factionId: 'zhang_lu', leadership: 65, strategy: 72, politics: 70, loyalty: 78 },
    { id: 'g_tao_qian', name: '陶谦', factionId: 'tao_qian', leadership: 60, strategy: 58, politics: 64, loyalty: 68 },
    { id: 'g_liu_biao', name: '刘表', factionId: 'liu_biao', leadership: 68, strategy: 70, politics: 80, loyalty: 76 },
    { id: 'g_liu_zhang', name: '刘璋', factionId: 'liu_zhang', leadership: 55, strategy: 50, politics: 62, loyalty: 74 },
];
